# Site settings
title: TVRCGO
description: "An engineer"
email: tvrcgo@gmail.com
keyword: ""
url: "http://tvrcgo.com"              # your host, for absolute URL
baseurl: "/"         # for example, '/blog' if your blog hosted on 'host/blog'

# Build settings
highlighter: rouge
permalink: /p/:title
paginate: 10
exclude: ["Gemfile", "Gemfile.lock"]
sass:
  style: compressed

# Gems
gems:
  - jekyll-mentions
  - jekyll-paginate

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
