# Site settings
title: TVRCGO
description: "An engineer"
email: tvrcgo@gmail.com
keyword: ""
url: "http://tvrcgo.com"              # your host, for absolute URL
baseurl: "/p"         # for example, '/blog' if your blog hosted on 'host/blog'

# Build settings
highlighter: rouge
permalink: /:year-:month-:day-:title
paginate: 10

# Gems
gems:
  - jekyll-mentions
  - jekyll-paginate

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
