# Site settings
title: TVRCGO
description: "An engineer"
email: tvrcgo@gmail.com
keyword: ""
url: "http://tvrcgo.com"              # your host, for absolute URL
baseurl: "/p"         # for example, '/blog' if your blog hosted on 'host/blog'

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
# permalink: /:year-:month-:day-:title
paginate: 10

# Gems
gems: [jekyll-paginate]

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
